name: DragonTag
version: '${project.version}'
main: com.unipi.alexandris.minecraftplugin.dragonrankplugin.DragonRank
api-version: 1.19
authors: [ Antitonius ]
description: A plugin implementing a Dragon Egg Tag Game with the help of UltraPermissions.
website: https://anthonyal.github.io
## This is required.
load: POSTWORLD
depend:
  - UltraPermissions
commands:
  dragon_keeper:
    description: Command group for Dragon Keeper.
    aliases: dk
    permission: dragon_keeper
permissions:
  dragon_keeper:
    description: Access to all Dragon Keeper commands.
    default: op
