name: DragonTag
version: '${project.version}'
main: com.unipi.alexandris.minecraftplugin.dragontagplugin.DragonTag
api-version: 1.19
authors: [ Antitonius ]
description: A plugin implementing a Dragon Egg Tag Game with the help of UltraPermissions.
website: https://anthonyal.github.io
## This is required.
load: POSTWORLD
depend:
  - UltraPermissions
softdepend:
  - PlaceholderAPI
commands:
  dragontag:
    description: Command group for Dragon Keeper.
    aliases: dt
    permission: dragontag.info
permissions:
  dragontag.admin:
    description: Access to all Dragon Keeper commands.
    default: op
    children:
      - dragontag.access
      - dragontag.info
  dragontag.access:
    description: Restricted access to /dt current remove, /dt current assign and /dt current reset.
    default: op
    children:
      - dragontag.info
  dragontag.info:
    description: Access to /dt and /dt current name.
    default: op


